package main

const LOCAL_KEY_SOCKS = "socks"
const LOCAL_KEY_CLIENTMODE = "clientMode"
const LOCAL_KEY_ENABLE = "enable"
const LOCAL_KEY_BINDADDR = "bindAddr"
const LOCAL_KEY_BINDPORT = "bindPort"
const LOCAL_KEY_USERNAME = "username"
const LOCAL_KEY_PASSWORD = "password"
const LOCAL_KEY_USEAUTH = "useAuth"
const LOCAL_KEY_USERDATABASE = "userDatabase"

var KEY_SOCKS_CLIENTMODE_ENABLE = []string{LOCAL_KEY_SOCKS, LOCAL_KEY_CLIENTMODE, LOCAL_KEY_ENABLE}
var KEY_SOCKS_CLIENTMODE_SERVERADDR = []string{LOCAL_KEY_SOCKS, LOCAL_KEY_CLIENTMODE, "serverAddr"}
var KEY_SOCKS_CLIENTMODE_SERVERPORT = []string{LOCAL_KEY_SOCKS, LOCAL_KEY_CLIENTMODE, "serverPort"}
var KEY_SOCKS_CLIENTMODE_USERNAME = []string{LOCAL_KEY_SOCKS, LOCAL_KEY_CLIENTMODE, LOCAL_KEY_USERNAME}
var KEY_SOCKS_CLIENTMODE_PASSWORD = []string{LOCAL_KEY_SOCKS, LOCAL_KEY_CLIENTMODE, LOCAL_KEY_PASSWORD}
var KEY_SOCKS_V4 = []string{LOCAL_KEY_SOCKS, "v4"}
var KEY_SOCKS_V4_ENABLE = []string{LOCAL_KEY_SOCKS, "v4", LOCAL_KEY_ENABLE}
var KEY_SOCKS_V4_BINDADDR = []string{LOCAL_KEY_SOCKS, "v4", LOCAL_KEY_BINDADDR}
var KEY_SOCKS_V4_BINDPORT = []string{LOCAL_KEY_SOCKS, "v4", LOCAL_KEY_BINDPORT}
var KEY_SOCKS_V5 = []string{LOCAL_KEY_SOCKS, "v5"}
var KEY_SOCKS_V5_ENABLE = []string{LOCAL_KEY_SOCKS, "v5", LOCAL_KEY_ENABLE}
var KEY_SOCKS_V5_BINDADDR = []string{LOCAL_KEY_SOCKS, "v5", LOCAL_KEY_BINDADDR}
var KEY_SOCKS_V5_BINDPORT = []string{LOCAL_KEY_SOCKS, "v5", LOCAL_KEY_BINDPORT}
var KEY_SOCKS_V5_USEAUTH = []string{LOCAL_KEY_SOCKS, "v5", LOCAL_KEY_USEAUTH}
var KEY_SOCKS_V5_USERDATABASE = []string{LOCAL_KEY_SOCKS, "v5", LOCAL_KEY_USERDATABASE}

